package main;

public interface R {
    String PRODUCER_PRODUCES = "PRODUCER_PRODUCES";
    String PRODUCER_WAIT = "PRODUCER_WAIT";
    String CONSUMER_CONSUME = "CONSUMER_CONSUME";
    String CONSUMER_WAIT = "CONSUMER_WAIT";
}
